"""create chapter 02 tables

Revision ID: fe2b1c0b91da
Revises:
Create Date: 2026-09-29 18:03:39.138691

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe2b1c0b91da"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "waiting_human", "closed", "failed", name="conversation_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_table(
        "faq",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("question", sa.String(length=255), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_faq_category"), "faq", ["category"], unique=False)
    op.create_index(op.f("ix_faq_question"), "faq", ["question"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "assistant", "tool", name="message_role"), nullable=False
        ),
        sa.Column("content", mysql.LONGTEXT(), nullable=False),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("tool_call_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("ticket_no", sa.String(length=32), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("issue_description", sa.Text(), nullable=False),
        sa.Column("ticket_type", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "processing", "resolved", "closed", name="ticket_status"),
            server_default="open",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("ticket_no"),
    )
    op.create_index(
        op.f("ix_tickets_conversation_id"), "tickets", ["conversation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickets")
    op.drop_table("messages")
    op.drop_table("faq")
    op.drop_table("conversations")
    # ### end Alembic commands ###
